#!/bin/sh
# Prevents from pushing directly to develop or master
NC='\033[0m'    # NO COLOR
LR='\033[1;31m' # LIGHT RED
LY='\033[1;33m' # LIGHT YELLOW

BRANCH=`git rev-parse --abbrev-ref HEAD`
PROTECTED_BRANCHES="^(master|develop)"

if [[ "$BRANCH" =~ $PROTECTED_BRANCHES ]]; then
	printf "${LR}[ERROR] You are not allowed to push code directly to protected branches.${NC}\n\n"
	printf "List of protected branches:\n"
	printf "${LY}master\ndevelop${NC}\n\n"
	printf "Push your code in separate branch and create pull request.\n"
	exit 1
fi

exit 0
